name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository source code
        uses: actions/checkout@v3
      - name: Check Node version
        run: node -v
      - name: Check files
        run: ls -al
      - name: Demo build - Install Dependencies
        run: yarn install
      - name: Demo build
        run: yarn build
  deploy:
    name: Build and deploy to EC2
    needs: checkout
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DOMAIN }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/tools
            git pull origin main
            yarn install
            yarn build
            pm2 restart all
